# Generated by Django 3.2 on 2023-04-30 20:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230430_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, message='Оценка должна быть больше 1'), django.core.validators.MaxValueValidator(10, message='Оценка должна быть меньше 10')], verbose_name='Оценка'),
        ),
    ]
