# Generated by Django 3.2 on 2023-04-30 22:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20230430_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, message='Оценка должна быть больше 1'), django.core.validators.MaxValueValidator(10, message='Оценка должна быть меньше 10')], verbose_name='Оценка'),
        ),
    ]
