# Generated by Django 3.2 on 2023-05-01 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_score'),
        ('reviews', '0006_auto_20230430_2225'),
    ]

    operations = [
    ]
